module.exports = {
	...process.pkg && { dbType: 'sqlite' },
	dbPath: 'db',
	dbHost: 'localhost',
	dbPort: 3306,
	dbName: 'panda',
	dbUser: 'root',
	dbPass: '69',
	port: 8880,
	cors: false,
	corsOrigin: '*',
	webui: true,
	webuiPath: 'frontend',
	features: { personal: !!process.pkg },
};
